name: 'jira-checklist-action'
description: 'ensures that linked JIRA issues have a completed checklist'
author: 'furkando'
inputs:
  project:
    required: true
    description: 'JIRA Project'
  jira-host:
    required: true
    description: 'JIRA Domain'
  jira-email:
    required: true
    description: 'JIRA Login'
  jira-api-token:
    required: true
    description: 'JIRA API Token'
runs:
  using: 'node16'
  main: 'dist/index.js'
