name: JIRA Checklist

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  enforce-issue-checklist:
    runs-on: ubuntu-latest
    name: JIRA Checklist
    steps:
      - uses: actions/checkout@v3
      - name: Check for JIRA issue checklist
        id: check
        uses: ./
        with:
          project: 'RNDK'
          jira-host: ${{ secrets.JIRA_HOST }}
          jira-email: ${{ secrets.JIRA_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}